title: "Michael Qian"
author: "Michael Qian"
description: "University of Southern California"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false  

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {title: "CV", url: "https://uchicago.box.com/s/z7uky0de7m65nz7usubx6xjccvm8oo3k"}
  - {file: "Projects.html", title: "Projects"}
  - {file: "Media.md", title: "Media"}
  #- {file: "Work.md", title: "Work"}
  - {title: "lAB", url: "https://sites.usc.edu/culbertson/"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:wanliqian965@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Silverwings-zero"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
